# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokeSpawns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Time Seen')),
                ('pokeid', models.IntegerField()),
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
                ('despawn_time', models.FloatField()),
            ],
        ),
    ]
